### ISSUE TITLE
LUA error on login 10.2.7: attempt to index field 'PetStableFrame' (a nil value)

### ISSUE THREAD

**Issue by RussB-626** [Benik/BenikUI#50] opened 2024-05-07 22:12 UTC
**Describe the bug and post the error message, if there is one**
LUA error on login 10.2.7: attempt to index field 'PetStableFrame' (a nil value)

**To Reproduce**
- Have the current version of BenikUI - The ElvUI Edit version 4.46 installed for WoW Retail version 10.2.6 installed
- Log into the game and verify LUA error pops up

**Expected behavior**
Self explanatory

**Screenshots**
![image](https://github.com/Benik/BenikUI/assets/37383310/d1c7b65f-89c8-4aed-9c4d-188873e0477e)

**Please include the addon and game versions:**
 - BenikUI: 4.46
 - ElvUI: v13.64
 - WoW game variation (retail, WotLK, Classic Era): retail 10.2.7

**Additional context**

```
Message: ...ace/AddOns/ElvUI_BenikUI/modules/styles/blizzard.lua:207: attempt to index field 'PetStableFrame' (a nil value)
Time: Tue May  7 18:04:19 2024
Count: 1
Stack: ...ace/AddOns/ElvUI_BenikUI/modules/styles/blizzard.lua:207: attempt to index field 'PetStableFrame' (a nil value)
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:2146: in function <Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:2141>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1822: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1863: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1973: in function <Interface/AddOns/ElvUI/Core/General/Core.lua:1942>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:307: in function <Interface/AddOns/ElvUI/Core/init.lua:306>
...
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:607: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: self = <table> {
 Blizzard_Channels = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Channels.lua:7
 Blizzard_ClassTalentUI = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/ClassTalents.lua:24
 HandleFrame = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:189
 ArrowRotation = <table> {
 }
 HandleNextPrevButton = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1363
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:147
 QuestFrameProgressItems_Update = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Quest.lua:329
 GuildInviteFrame = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Guild.lua:217
 MirrorTimers = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/MirrorTimers.lua:34
 Ace3_ColorizeEnable = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Ace3.lua:527
 AlertSystem = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/Alerts.lua:788
 HandleIcon = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1299
 Blizzard_WeeklyRewards = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/WeeklyRewards.lua:57
 SetDisabledBackdrop = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:295
 HandleCategoriesButtons = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:82
 Blizzard_PlayerChoice = <function> defined @Interface/AddOns/ElvUI/Mainline/Modules/Skins/PlayerChoice.lua:140
 ADDON_LOADED = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:2063
 HandleSlider
```

**Comment by E-Tsx** [comment] 2024-05-08 01:42
I just pushed a fix for this on repo, you can use this untill benik does a release for 10.2.7

**Comment by WoWGIRL83** [comment] 2024-05-09 11:18
I'm having the same issue since the newest wow update.

**Comment by crypticasden** [comment] 2024-05-09 17:08
Describe the bug and post the error message, if there is one
LUA error on login 10.2.7: attempt to index field 'PetStableFrame' (a nil value)


Message: ...ace/AddOns/ElvUI_BenikUI/modules/styles/blizzard.lua:207: attempt to index field 'PetStableFrame' (a nil value)
Time: Thu May  9 11:49:07 2024
Count: 1
Stack: ...ace/AddOns/ElvUI_BenikUI/modules/styles/blizzard.lua:207: attempt to index field 'PetStableFrame' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI_BenikUI/modules/styles/blizzard.lua"]:207: in function <...ace/AddOns/ElvUI_BenikUI/modules/styles/blizzard.lua:11>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:2146: in function <Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:2141>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1822: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1863: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1973: in function <Interface/AddOns/ElvUI/Core/General/Core.lua:1942>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:307: in function <Interface/AddOns/ElvUI/Core/init.lua:306>
[string "=[C]"]: ?
...
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:402: in function `UIParentLoadAddOn'
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:607: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: (*temporary) = <function> defined =[C]:-1



To Reproduce

Have the current version of BenikUI - The ElvUI Edit version 4.46 installed for WoW Retail version 10.2.6 installed
Log into the game and verify LUA error pops up
Expected behavior
Self explanatory

![image](https://github.com/Benik/BenikUI/assets/29047474/f6229c88-9497-4b17-9bd9-84461c6fd4ff)




BenikUI: 4.46
ElvUI: v13.64
WoW game variation (retail, WotLK, Classic Era): retail 10.2.7

**Comment by Repooc** [comment] 2024-05-09 17:39
currently been fixed in the dev branch and will be in the next release

**Closed by Repooc** 2024-05-09 17:39 UTC
